# arguments for dataset
dataset: ade20k
data_root: Your/ADE20K/Path
nclass: 150
crop_size: 518

# arguments for training
epochs: 60
batch_size: 2 # per GPU x 4 GPUs
lr: 0.000005
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: dpt
backbone: dinov2_small
lock_backbone: True
