# arguments for dataset
dataset: cityscapes
data_root: Your/Cityscapes/Path
nclass: 19
crop_size: 798

# arguments for training
epochs: 180
batch_size: 2 # per GPU x 4 GPUs
lr: 0.000005
lr_multi: 40.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
conf_thresh: 0.95

# arguments for model
model: dpt
backbone: dinov2_small
lock_backbone: False
